on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout repo to the runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: |
          python migrate.py . _migrated True
          python custom-build-script.py
          sphinx-build -b html ./_migrated/ _build/html
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "github action auto build" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_KEY}}
          accountId: ${{ secrets.CF_ACCOUNT_ID}}
          projectName: NAME_OF_PROJECT
          branch: main
          directory: output
